CREATE TABLE IF NOT EXISTS projects(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL CHECK (name <> ''),
  priority INTEGER NOT NULL,
  description TEXT,
  delivarydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL CHECK (name <> ''),
  done BOOLEAN,
  projectId INTEGER REFERENCES projects(id)
);

-- INSERT PROJECTS DATA
INSERT INTO projects(name, priority, description, delivarydate)
  VALUES('Make web app', 1, 'Using JS', '2021-08-24')

-- INSERT TASKS DATA
INSERT INTO tasks(name, done, projectId)
  VALUES('Download insomnia', false, 1)

INSERT INTO tasks(name, done, projectId)
  VALUES('Download postgress', false, 1)